language: rust

rust:
  - nightly

env:
  - NODE_VERSION="8"

before_install:
  - nvm install $NODE_VERSION

install:
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo install cargo-web
  - yarn install

script: npm run compile